# Task writes "some stuff" to a predefined path in the workspace git PipelineResource
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: get-json
spec:
  inputs:
    params:
      - name: apikey
        description: the ibmcloud api key
      - name: api
        description: the ibmcloud api endpoint
        default: "https://cloud.ibm.com"
      - name: region
        description: the ibmcloud registry region
      - name: toolchainID
        description: the toolchain id
    resources:
    - name: workspace
      type: git
  outputs:
    resources:
    - name: workspace
      type: git
  steps:
  - name: login-and-get
    image: ubuntu
    env:
      - name: IBMCLOUD_API_KEY
        value: $(inputs.params.apikey)
      - name: API
        value: $(inputs.params.api)
      - name: REGION
        value: $(inputs.params.region)
      - name: TOOLCHAIN_ID
        value: $(inputs.params.toolchainID)
    command: ["/bin/bash"]
    args:
      - ibmcloud login --apikey $IBMCLOUD_API_KEY;
---
#The Output of the first Task (git resource) create-file is given as an `Input`
# to the next `Task` check-stuff-file-exists using`from` clause.
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: output-pipeline
spec:
  resources:
  - name: source-repo
    type: git
  tasks:
  - name: get-toolchain-json          # 1. create file
    taskRef:
      name: get-json
    resources:
      inputs:
      - name: workspace
        resource: source-repo
      outputs:
      - name: workspace
        resource: source-repo
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipeline-template
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
    - name: message
      description: The message to print
      default: This is the default message
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: git-source-$(uid)
        labels:
          triggertemplated: "true"
          generatedBy: "triggers-example"
      spec:
        type: git
        params:
        - name: revision
          value: $(params.gitrevision)
        - name: url
          value: $(params.gitrepositoryurl)
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        generateName: output-pipeline-run
        labels:
          triggertemplated: "true"
          generatedBy: "triggers-example"
      spec:
        pipelineRef:
            name: output-pipeline
        serviceAccount: 'default'
        params:
        - name: message
          value: $(params.message)
        resources:
        - name: source-repo
          resourceRef:
            name: git-source-$(uid)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: pipeline-binding
spec:
  params:
    - name: gitrevision
      value: $(event.head_commit.id)
    - name: gitrepositoryurl
      value: $(event.repository.url)
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener
spec:
  triggers:
    - binding:
        name: pipeline-binding
      template:
        name: pipeline-template
      params:
        - name: message
          value: Hello from the Git Triggers EventListener!
